
title: Sorting things here and there 
author:
  name: Camilla Lindelöw
  email: camilla.lindelow@hb.se

theme: minima

minima:
  skin: solarized-light
  
  nav_pages:
    - about.md
    - portfolio.md


