
title: Sorting things here and there 
author:
  name: Camilla Lindelöw
  email: camilla.lindelow@hb.se

remote_theme: jekyll/minima@d4d779a

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: solarized-light
  
  nav_pages:
    - about.md
    - portfolio.md


